insert into public.organization (id, name, plan) values ('org_fd', 'Floor Daddy', 'internal') on conflict (id) do nothing;

insert into public.module (key, name, icon, sort_order, is_core) values
  ('dashboard', 'Dashboard', 'LayoutDashboard', 10, true),
  ('appointments', 'Appointments', 'CalendarClock', 20, true),
  ('leads', 'Leads', 'UserPlus', 30, false),
  ('customers', 'Customers', 'Users', 40, false),
  ('sales', 'Sales', 'DollarSign', 50, false),
  ('quotes', 'Quotes', 'FileText', 60, false),
  ('projects', 'Projects', 'Hammer', 70, false),
  ('journey', 'Journey', 'Map', 80, false),
  ('order_processing', 'Order Processing', 'ClipboardList', 90, false),
  ('tickets', 'Tickets', 'Ticket', 100, false),
  ('fleet', 'Fleet', 'Truck', 110, false),
  ('communication', 'Communication', 'MessageSquare', 120, false),
  ('reports', 'Reports', 'BarChart3', 130, false),
  ('finance', 'Finance', 'TrendingUp', 140, false),
  ('team', 'Team', 'UserCog', 150, false),
  ('settings', 'Settings', 'Settings', 160, true),
  ('logs', 'Logs', 'ScrollText', 170, false)
on conflict (key) do update set name=excluded.name, icon=excluded.icon, sort_order=excluded.sort_order;

insert into public.app_page (key, module_key, label, route_path, is_public, min_permission) values
  ('Dashboard', 'dashboard', 'Dashboard', '/Dashboard', false, 'view'),
  ('Appointments', 'appointments', 'Appointments', '/Appointments', false, 'view'),
  ('AppointmentDetail', 'appointments', 'Appointment Detail', '/AppointmentDetail', false, 'view'),
  ('AppointmentReports', 'appointments', 'Appointment Reports', '/AppointmentReports', false, 'view'),
  ('AppointmentRehashReport', 'appointments', 'Appointment Rehash Report', '/AppointmentRehashReport', false, 'view'),
  ('MyAppointments', 'appointments', 'My Appointments', '/MyAppointments', false, 'view'),
  ('CancelledAppointments', 'appointments', 'Cancelled Appointments', '/CancelledAppointments', false, 'view'),
  ('RescheduledAppointments', 'appointments', 'Rescheduled Appointments', '/RescheduledAppointments', false, 'view'),
  ('ScheduledThisWeek', 'appointments', 'Scheduled This Week', '/ScheduledThisWeek', false, 'view'),
  ('AppointmentSettingChecklists', 'appointments', 'Appointment Setting Checklists', '/AppointmentSettingChecklists', false, 'view'),
  ('ConsultantAppointmentView', 'appointments', 'Consultant Appointment View', '/ConsultantAppointmentView', true, 'view'),
  ('LeadAppointmentView', 'appointments', 'Lead Appointment View', '/LeadAppointmentView', true, 'view'),
  ('ChecklistDetail', 'appointments', 'Checklist Detail', '/ChecklistDetail', false, 'view'),
  ('ChecklistV2Detail', 'appointments', 'Checklist V2 Detail', '/ChecklistV2Detail', false, 'view'),
  ('RecordingDetail', 'appointments', 'Recording Detail', '/RecordingDetail', false, 'view'),
  ('Recordings', 'appointments', 'Recordings', '/Recordings', false, 'view'),
  ('MyTasks', 'appointments', 'My Tasks', '/MyTasks', false, 'view'),
  ('ScheduleAssistant', 'appointments', 'Schedule Assistant', '/ScheduleAssistant', false, 'view'),
  ('Leads', 'leads', 'Leads', '/Leads', false, 'view'),
  ('LeadDetail', 'leads', 'Lead Detail', '/LeadDetail', false, 'view'),
  ('Customers', 'customers', 'Customers', '/Customers', false, 'view'),
  ('CustomerDetail', 'customers', 'Customer Detail', '/CustomerDetail', false, 'view'),
  ('CustomerProjectView', 'customers', 'Customer Project View', '/CustomerProjectView', true, 'view'),
  ('CompanyDirectory', 'customers', 'Company Directory', '/CompanyDirectory', false, 'view'),
  ('Sales', 'sales', 'Sales', '/Sales', false, 'view'),
  ('SaleDetail', 'sales', 'Sale Detail', '/SaleDetail', false, 'view'),
  ('MySales', 'sales', 'My Sales', '/MySales', false, 'view'),
  ('SalesByConsultant', 'sales', 'Sales By Consultant', '/SalesByConsultant', false, 'view'),
  ('SalesReports', 'sales', 'Sales Reports', '/SalesReports', false, 'view'),
  ('ManualSalesContractView', 'sales', 'Manual Sales Contract View', '/ManualSalesContractView', true, 'view'),
  ('ManualDesignMods', 'sales', 'Manual Design Mods', '/ManualDesignMods', false, 'view'),
  ('DesignModView', 'sales', 'Design Mod View', '/DesignModView', true, 'view'),
  ('MyQuotes', 'quotes', 'My Quotes', '/MyQuotes', false, 'view'),
  ('QuoteDetail', 'quotes', 'Quote Detail', '/QuoteDetail', false, 'view'),
  ('Projects', 'projects', 'Projects', '/Projects', false, 'view'),
  ('ProjectDetail', 'projects', 'Project Detail', '/ProjectDetail', false, 'view'),
  ('CancelledProjects', 'projects', 'Cancelled Projects', '/CancelledProjects', false, 'view'),
  ('ClaimsDashboard', 'projects', 'Claims Dashboard', '/ClaimsDashboard', false, 'view'),
  ('PreInstallChecklistView', 'projects', 'Pre Install Checklist View', '/PreInstallChecklistView', true, 'view'),
  ('Journey', 'journey', 'Journey', '/Journey', false, 'view'),
  ('JourneyProjectDetail', 'journey', 'Journey Project Detail', '/JourneyProjectDetail', false, 'view'),
  ('OrderProcessing', 'order_processing', 'Order Processing', '/OrderProcessing', false, 'view'),
  ('OrderProcessingReports', 'order_processing', 'Order Processing Reports', '/OrderProcessingReports', false, 'view'),
  ('ContractDiscrepancy', 'order_processing', 'Contract Discrepancy', '/ContractDiscrepancy', false, 'view'),
  ('RFMSCustomers', 'order_processing', 'RFMS Customers', '/RFMSCustomers', false, 'view'),
  ('MyTickets', 'tickets', 'My Tickets', '/MyTickets', false, 'view'),
  ('SubmitTicket', 'tickets', 'Submit Ticket', '/SubmitTicket', true, 'view'),
  ('RequesterTicketView', 'tickets', 'Requester Ticket View', '/RequesterTicketView', true, 'view'),
  ('DesignConsultantTicketView', 'tickets', 'Design Consultant Ticket View', '/DesignConsultantTicketView', true, 'view'),
  ('Fleet', 'fleet', 'Fleet', '/Fleet', false, 'view'),
  ('FleetVehicles', 'fleet', 'Fleet Vehicles', '/FleetVehicles', false, 'view'),
  ('FleetDrivers', 'fleet', 'Fleet Drivers', '/FleetDrivers', false, 'view'),
  ('FleetMaintenance', 'fleet', 'Fleet Maintenance', '/FleetMaintenance', false, 'view'),
  ('CommunicationHub', 'communication', 'Communication Hub', '/CommunicationHub', false, 'view'),
  ('Reports', 'reports', 'Reports', '/Reports', false, 'view'),
  ('DCPerformanceMatrix', 'reports', 'DC Performance Matrix', '/DCPerformanceMatrix', false, 'view'),
  ('MarketingPerformance', 'reports', 'Marketing Performance', '/MarketingPerformance', false, 'view'),
  ('Finance', 'finance', 'Finance', '/Finance', false, 'view'),
  ('GrossProfitReport', 'finance', 'Gross Profit Report', '/GrossProfitReport', false, 'view'),
  ('CashFlowProjection', 'finance', 'Cash Flow Projection', '/CashFlowProjection', false, 'view'),
  ('Calculators', 'finance', 'Calculators', '/Calculators', false, 'view'),
  ('InvoiceCalculator', 'finance', 'Invoice Calculator', '/InvoiceCalculator', false, 'view'),
  ('TeamMembers', 'team', 'Team Members', '/TeamMembers', false, 'view'),
  ('TeamMemberDetail', 'team', 'Team Member Detail', '/TeamMemberDetail', false, 'view'),
  ('DesignConsultants', 'team', 'Design Consultants', '/DesignConsultants', false, 'view'),
  ('CustomerServiceReps', 'team', 'Customer Service Reps', '/CustomerServiceReps', false, 'view'),
  ('Settings', 'settings', 'Settings', '/Settings', false, 'view'),
  ('Logs', 'logs', 'Logs', '/Logs', false, 'view')
on conflict (key) do update set module_key=excluded.module_key, label=excluded.label, is_public=excluded.is_public;

insert into public.role (id, org_id, key, name, sort_order, is_system) values
  ('role_admin', 'org_fd', 'admin', 'Administrator', 10, true),
  ('role_sales_manager', 'org_fd', 'sales_manager', 'Sales Manager', 20, false),
  ('role_design_consultant', 'org_fd', 'design_consultant', 'Design Consultant', 30, false),
  ('role_customer_service_rep', 'org_fd', 'customer_service_rep', 'Customer Service Rep', 40, false),
  ('role_order_processor', 'org_fd', 'order_processor', 'Order Processor', 50, false),
  ('role_finance_manager', 'org_fd', 'finance_manager', 'Finance Manager', 60, false),
  ('role_operations', 'org_fd', 'operations', 'Operations', 70, false),
  ('role_project_manager', 'org_fd', 'project_manager', 'Project Manager', 80, false),
  ('role_customer_experience', 'org_fd', 'customer_experience', 'Customer Experience', 90, false)
on conflict (id) do update set name=excluded.name, sort_order=excluded.sort_order;

insert into public.role_module_permission (id, role_id, module_key, permission) values
  ('role_admin_dashboard', 'role_admin', 'dashboard', 'admin'),
  ('role_admin_appointments', 'role_admin', 'appointments', 'admin'),
  ('role_admin_leads', 'role_admin', 'leads', 'admin'),
  ('role_admin_customers', 'role_admin', 'customers', 'admin'),
  ('role_admin_sales', 'role_admin', 'sales', 'admin'),
  ('role_admin_quotes', 'role_admin', 'quotes', 'admin'),
  ('role_admin_projects', 'role_admin', 'projects', 'admin'),
  ('role_admin_journey', 'role_admin', 'journey', 'admin'),
  ('role_admin_order_processing', 'role_admin', 'order_processing', 'admin'),
  ('role_admin_tickets', 'role_admin', 'tickets', 'admin'),
  ('role_admin_fleet', 'role_admin', 'fleet', 'admin'),
  ('role_admin_communication', 'role_admin', 'communication', 'admin'),
  ('role_admin_reports', 'role_admin', 'reports', 'admin'),
  ('role_admin_finance', 'role_admin', 'finance', 'admin'),
  ('role_admin_team', 'role_admin', 'team', 'admin'),
  ('role_admin_settings', 'role_admin', 'settings', 'admin'),
  ('role_admin_logs', 'role_admin', 'logs', 'admin'),
  ('role_sales_manager_sales', 'role_sales_manager', 'sales', 'admin'),
  ('role_sales_manager_quotes', 'role_sales_manager', 'quotes', 'admin'),
  ('role_sales_manager_leads', 'role_sales_manager', 'leads', 'admin'),
  ('role_sales_manager_customers', 'role_sales_manager', 'customers', 'edit'),
  ('role_sales_manager_appointments', 'role_sales_manager', 'appointments', 'edit'),
  ('role_sales_manager_reports', 'role_sales_manager', 'reports', 'view'),
  ('role_sales_manager_finance', 'role_sales_manager', 'finance', 'view'),
  ('role_sales_manager_dashboard', 'role_sales_manager', 'dashboard', 'view'),
  ('role_design_consultant_appointments', 'role_design_consultant', 'appointments', 'edit'),
  ('role_design_consultant_leads', 'role_design_consultant', 'leads', 'edit'),
  ('role_design_consultant_customers', 'role_design_consultant', 'customers', 'edit'),
  ('role_design_consultant_quotes', 'role_design_consultant', 'quotes', 'edit'),
  ('role_design_consultant_communication', 'role_design_consultant', 'communication', 'view'),
  ('role_design_consultant_dashboard', 'role_design_consultant', 'dashboard', 'view'),
  ('role_customer_service_rep_appointments', 'role_customer_service_rep', 'appointments', 'edit'),
  ('role_customer_service_rep_customers', 'role_customer_service_rep', 'customers', 'edit'),
  ('role_customer_service_rep_communication', 'role_customer_service_rep', 'communication', 'edit'),
  ('role_customer_service_rep_tickets', 'role_customer_service_rep', 'tickets', 'edit'),
  ('role_customer_service_rep_leads', 'role_customer_service_rep', 'leads', 'view'),
  ('role_customer_service_rep_dashboard', 'role_customer_service_rep', 'dashboard', 'view'),
  ('role_order_processor_order_processing', 'role_order_processor', 'order_processing', 'admin'),
  ('role_order_processor_projects', 'role_order_processor', 'projects', 'edit'),
  ('role_order_processor_sales', 'role_order_processor', 'sales', 'view'),
  ('role_order_processor_customers', 'role_order_processor', 'customers', 'view'),
  ('role_order_processor_dashboard', 'role_order_processor', 'dashboard', 'view'),
  ('role_finance_manager_finance', 'role_finance_manager', 'finance', 'admin'),
  ('role_finance_manager_reports', 'role_finance_manager', 'reports', 'admin'),
  ('role_finance_manager_sales', 'role_finance_manager', 'sales', 'view'),
  ('role_finance_manager_dashboard', 'role_finance_manager', 'dashboard', 'view'),
  ('role_operations_projects', 'role_operations', 'projects', 'edit'),
  ('role_operations_journey', 'role_operations', 'journey', 'edit'),
  ('role_operations_fleet', 'role_operations', 'fleet', 'edit'),
  ('role_operations_order_processing', 'role_operations', 'order_processing', 'edit'),
  ('role_operations_reports', 'role_operations', 'reports', 'view'),
  ('role_operations_dashboard', 'role_operations', 'dashboard', 'view'),
  ('role_project_manager_projects', 'role_project_manager', 'projects', 'admin'),
  ('role_project_manager_journey', 'role_project_manager', 'journey', 'edit'),
  ('role_project_manager_appointments', 'role_project_manager', 'appointments', 'view'),
  ('role_project_manager_customers', 'role_project_manager', 'customers', 'view'),
  ('role_project_manager_communication', 'role_project_manager', 'communication', 'view'),
  ('role_project_manager_dashboard', 'role_project_manager', 'dashboard', 'view'),
  ('role_customer_experience_communication', 'role_customer_experience', 'communication', 'admin'),
  ('role_customer_experience_tickets', 'role_customer_experience', 'tickets', 'admin'),
  ('role_customer_experience_customers', 'role_customer_experience', 'customers', 'view'),
  ('role_customer_experience_projects', 'role_customer_experience', 'projects', 'view'),
  ('role_customer_experience_dashboard', 'role_customer_experience', 'dashboard', 'view')
on conflict (role_id, module_key) do update set permission=excluded.permission;

insert into public.org_module_entitlement (org_id, module_key, is_enabled)
select 'org_fd', key, true from public.module
on conflict (org_id, module_key) do nothing;
