-- Installer onboarding: fill-in-ready agreement templates. Replaces the raw blank-line
-- consent_text with {{placeholder}} templates that esign fills with the applicant's Subcontractor
-- Profile at signing-creation time, and drops the redundant blank signature blocks (esign captures
-- the real signature + audit trail). See DOC_MAP.fill in supabase/functions/esign/index.ts.
update public.esign_document_type set consent_text = $FD01$INDEPENDENT SUBCONTRACTOR MASTER AGREEMENT
Floor Daddy, LLC · Arizona ROC License No. 352055
THIS INDEPENDENT SUBCONTRACTOR MASTER AGREEMENT (this “Agreement”) is made and entered into as of {{effective_date}} (the “Effective Date”), by and between FLOOR DADDY, LLC, an Arizona limited liability company holding Arizona ROC License No. 352055, with its principal place of business at 3910 S Rural Rd, Suite 104, Tempe, Arizona 85282 (“Floor Daddy”), and {{subcontractor_name}}, a {{entity_type}} organized under the laws of the State of {{state_of_org}} (“Subcontractor”). Floor Daddy and Subcontractor are each a “Party” and together the “Parties.”
RECITALS
A. Floor Daddy is a licensed Arizona contractor engaged in the sale and installation of flooring in dwellings and other structures, and contracts directly with its customers for that work.
B. Subcontractor is an independently owned and operated business, separately licensed by the Arizona Registrar of Contractors, that holds itself out to the public as available to perform flooring installation services for multiple customers.
C. Floor Daddy wishes to engage Subcontractor from time to time, on a project-by-project basis, to perform a portion of the services Floor Daddy has contracted to provide to its customers, and Subcontractor wishes to be available for such engagements as an independent contractor.
D. The Parties intend that this Agreement, together with the accompanying documents identified in Section 1.5, set out all terms governing their relationship.
NOW, THEREFORE, in consideration of the mutual covenants and promises set out below, and other good and valuable consideration, the receipt and sufficiency of which are acknowledged, the Parties agree as follows:
1. BACKGROUND AND STRUCTURE
1.1 Floor Daddy contracts with homeowners and other customers (“Customers”) to furnish and install flooring in dwellings and other structures (each a “Project”). Floor Daddy wishes to engage Subcontractor, as an independent business, to perform installation services on certain Projects, and Subcontractor wishes to accept such engagements.
1.2 Master terms, project-by-project engagements. This Agreement sets the terms that govern every engagement between the Parties. It does not itself obligate Subcontractor to perform any work or obligate Floor Daddy to offer any. Each engagement arises only when Floor Daddy issues, and Subcontractor accepts, a written work order (a “Work Order”). Each accepted Work Order is a separate contract incorporating these terms.
1.3 Non-exclusive both ways. Floor Daddy does not require Subcontractor to work exclusively for Floor Daddy and expects that Subcontractor performs services for other parties. Subcontractor has the right to accept or decline any Work Order. Floor Daddy may retain other subcontractors for any Project, at any location, at any time, and is not obligated to offer any minimum volume of work.
1.5 Subcontractor Profile and accompanying documents. Subcontractor’s legal name, entity type, taxpayer identification number, ROC license number and classifications, insurance carriers and expiration dates, contact information, and designated payee name are recorded in Floor Daddy’s contractor management system (the “Subcontractor Profile”) through Floor Daddy’s onboarding process rather than in this Agreement. Subcontractor certifies that the information in its Subcontractor Profile is complete and accurate, and will notify Floor Daddy in writing of any change within five (5) business days. Subcontractor’s legal name in the Subcontractor Profile must match the name on its Arizona contractor’s license, the name associated with the taxpayer identification number it provides, and the name appearing on all payments issued by Floor Daddy. The following documents accompany and form part of the Parties’ agreement:
Exhibits A through E to this Agreement.
The Claims and Warranty Agreement, governing warranty claims and post-engagement obligations.
The Direct Deposit and ACH Payment Authorization, if Subcontractor elects electronic payment.
Each accepted Work Order.
1.4 Order of precedence. In a conflict, the order of control is: (a) this Agreement, (b) the Claims and Warranty Agreement, (c) the applicable Work Order, (d) the Exhibits, (e) all other documents. A Work Order may state the scope, schedule, and price for a Project, but may not modify the terms of this Agreement unless signed by both Parties as an amendment.
2. DEFINITIONS
“Completion” means the date on which all of the following have occurred: (a) Subcontractor has finished all Services under a Work Order; (b) Floor Daddy’s field manager has conducted a Final Walkthrough with the Customer; (c) the Customer has signed the Final Walkthrough acceptance; (d) all punch items identified at that Final Walkthrough have been cured; and (e) Subcontractor has delivered the complete close-out package described in Exhibit A.
“Final Walkthrough” means the walkthrough Floor Daddy’s field manager conducts with the Customer at the conclusion of a Project, at which the installed floor is inspected room by room, punch items are identified and marked, dated photographs are taken, and the Customer signs an acceptance. The signed Final Walkthrough record is the baseline against which any later warranty claim is evaluated under the Claims and Warranty Agreement.
“Corrective Services” means work required to correct, repair, or replace Services that do not conform to this Agreement.
“Dwelling” has the meaning given in A.R.S. § 12-1361.
“Services” means the work and materials Subcontractor is to provide under a Work Order, which will generally include some or all of the following:
Removing existing flooring of laminate, tile, wood, vinyl, LVP, or carpet in specified locations, and hauling away and disposing of all removed flooring.
Moving furniture, appliances, and toilets as necessary, and returning them to their original location and condition.
Removing baseboards and installing baseboards furnished by Floor Daddy.
Patching, repairing, or replacing subfloor as necessary for proper installation.
Installing new flooring materials furnished by Floor Daddy.
Any additional scope stated in the Work Order.
“Work Order” means a written scope, schedule, and price issued by Floor Daddy for a specific Project and accepted by Subcontractor. Acceptance may be by signature, written confirmation, or Subcontractor’s commencement of the Services.
3. INDEPENDENT CONTRACTOR STATUS
3.1 Independent business. Subcontractor operates its own independent business. In performing the Services, Subcontractor is independent of Floor Daddy in the execution of the work and is not subject to the rule or control of Floor Daddy. Subcontractor is engaged only in the performance of a definite job or piece of work and is subordinate to Floor Daddy only in achieving a result consistent with Floor Daddy’s design, within the meaning of A.R.S. § 23-902(C).
3.2 No authority to supervise or control. Floor Daddy does not have the authority to supervise or control the actual work of Subcontractor or Subcontractor’s employees. Subcontractor has the sole right and obligation to control the manner, means, method, and sequence of performance, to determine the days and time periods it works within any window agreed in a Work Order, and to select, direct, discipline, and pay its own personnel.
3.3 Quality standards and deadlines are not control. Floor Daddy retains the right to specify the result, to impose quality standards, and to set completion deadlines. Any direction, standard, or requirement that Floor Daddy imposes in order to comply with a federal or state statute, rule, code, licensing requirement, or manufacturer specification is not evidence of an employment relationship, consistent with A.R.S. § 23-1602.
3.4 No employment benefits. Subcontractor and its personnel are not employees of Floor Daddy and are not entitled to any benefit arising from an employment relationship, including unemployment benefits, health coverage, paid leave, or workers’ compensation benefits from Floor Daddy. Subcontractor is responsible for all tax liability associated with payments it receives, and Floor Daddy will not withhold taxes. Floor Daddy will issue a Form 1099 as required.
3.5 Separate operations. Subcontractor maintains its own business operations, tools, vehicles, and equipment, and will not combine its business operations with Floor Daddy’s. Subcontractor is responsible for all expenses it incurs in performing the Services.
3.6 Annual attestation. On execution and annually thereafter, Subcontractor will confirm in its Subcontractor Profile that during the preceding twelve months it performed, or held itself available to perform, flooring services for customers other than Floor Daddy, and that it continues to operate an independent business open to work from others.
3.7 Workers’ compensation agreement. The Parties will also execute Exhibit D, an independent contractor agreement under A.R.S. § 23-902(D). The terms of this Agreement apply to Subcontractor, Subcontractor’s employees, and Subcontractor’s own independent contractors.
4. LICENSING AND LEGAL COMPLIANCE
4.1 License required. Subcontractor must hold, at the time of acceptance of every Work Order and continuously throughout performance, an active Arizona Registrar of Contractors license in every classification required for the scope assigned. Floor Daddy does not provide Subcontractor with any business registration or license.
4.2 Classification matters. Subcontractor acknowledges that floor covering work requires an R-8, C-8, or CR-8 license, and that ceramic, plastic, and metal tile work requires a separate R-48, C-48, or CR-48 license. Subcontractor will not accept or perform any scope outside the classifications it actually holds, and will notify Floor Daddy in writing before declining scope on that basis so the Work Order can be reassigned.
4.3 No reliance on the minor work exemption. Subcontractor acknowledges that the exemption in A.R.S. § 32-1121(A)(14) does not apply to work that is part of a larger or major operation, and that all Services under this Agreement are part of Floor Daddy’s larger Project.
4.4 Verification and lapse. Subcontractor will upload a current copy of its ROC license and bond to its Subcontractor Profile before the first Work Order and at each renewal, and Floor Daddy may verify status directly with the Registrar of Contractors at any time. Subcontractor will notify Floor Daddy in writing within two business days of any suspension, revocation, lapse, non-renewal, complaint, or citation affecting its license. Floor Daddy may suspend Work Orders immediately upon any lapse.
4.5 Personnel. All persons performing the Services must be qualified, competent, and lawfully authorized to work. Subcontractor is solely responsible for verifying employment eligibility for its own employees and for all wage, hour, and payroll obligations owed to them.
4.6 Lower tier. Subcontractor will not delegate or further subcontract any Services without Floor Daddy’s prior written consent. Any approved lower-tier subcontractor must be separately licensed in the required classification, must carry the insurance required by Section 10, and must agree in writing to be bound by this Agreement, with Floor Daddy named an intended third-party beneficiary.
4.7 General compliance. Subcontractor will comply with all applicable laws, ordinances, and building codes, including the Uniform Building Code and local amendments, and with the minimum workmanship standards published by the Arizona Registrar of Contractors.
5. PERFORMANCE STANDARDS
5.1 Standard of work. Subcontractor will perform the Services in accordance with the Work Order, in a good and workmanlike manner, in accordance with industry standards, in compliance with all applicable codes, and meeting or exceeding the manufacturer’s or supplier’s published standards and specifications for the materials installed.
5.2 Site verification. By accepting a Work Order, Subcontractor confirms that it has reviewed the scope, that the scope is clear and unambiguous, and that it will verify field conditions and measurements at the start of the job. Subcontractor will notify Floor Daddy of any material shortage, discrepancy between the Work Order and actual conditions, or unforeseen condition before proceeding with affected work. Work performed outside the Work Order without prior written authorization is at Subcontractor’s cost.
5.3 Schedule. Each Work Order will state an expected start date, an expected completion date, and any arrival window the Customer has agreed to. Subcontractor determines its own daily schedule within that window and is responsible for meeting the completion date. If Subcontractor will not meet an agreed window or completion date, it will notify Floor Daddy and the Customer as far in advance as practicable.
5.4 Jobsite standards. Subcontractor will meet the jobsite, customer interaction, protection, cleanup, and close-out standards in Exhibit A. These standards define required results and code compliance and do not give Floor Daddy authority over the manner or means of the work.
5.5 Inspection. Floor Daddy may observe, inspect, or test the Services at any time. Inspection is for Floor Daddy’s benefit only. Failure to discover a defect does not waive any of Subcontractor’s obligations. Subcontractor will cooperate with any inspection.
5.6 Change orders. If a Customer requests a change, Floor Daddy will give Subcontractor written notice as soon as practicable. Any increase or decrease in the price must be agreed in writing and signed by both Parties before the changed work proceeds. If the Parties cannot agree on price, Floor Daddy may remove Subcontractor from that Project, and Subcontractor will be paid a pro rata amount for Services actually performed in accordance with this Agreement.
6. PRICING
6.1 Pricing schedule. Unit pricing is set out in Exhibit B and applies to every Work Order unless the Work Order states otherwise. Exhibit B may be amended only in a writing signed by both Parties, with at least [14] days’ advance notice of any reduction to existing rates.
6.2 Materials. Floor Daddy furnishes flooring products and adhesives for glue-down products as stated in Exhibit B. Subcontractor furnishes setting materials, shower materials, concrete products, and all tools, equipment, vehicles, consumables, and personal protective equipment. Floor Daddy does not provide tools to Subcontractor.
6.3 Basis of payment. Subcontractor is paid by the piece and by the job at the rates in Exhibit B. Subcontractor is not paid a salary and is not guaranteed any minimum or regular payment.
7. PAYMENT
7.1 Invoicing. Subcontractor will submit an invoice or payment request identifying the Work Order and the units completed, together with the close-out package required by Exhibit A.
7.2 Payment timing. Floor Daddy will pay Subcontractor, less any retention under Section 7.4 and any offset properly noticed under Section 7.6:
within seven (7) days after Floor Daddy receives payment from the Customer for the Project, consistent with A.R.S. § 32-1129.02; and
in all events, no later than thirty (30) days after Completion, whether or not the Customer has paid, except to the extent the Customer’s non-payment is caused by Subcontractor’s defective or incomplete Services and Floor Daddy has issued the written statement required by Section 7.6.
7.3 Payee. Payment will be issued in the name appearing on this Agreement and on Subcontractor’s Form W-9. Direct deposit is optional and is governed by the separate Direct Deposit and ACH Payment Authorization.
7.4 Retention. Floor Daddy will withhold five percent (5%) of each payment, up to a cumulative maximum of $2,500 across all Projects (the “Retention”). Floor Daddy will release the Retention balance attributable to a Project, less amounts properly offset under Section 7.6, within ninety (90) days after Completion of that Project. Subcontractor need not submit a separate request for release.
7.5 Customer funds. Floor Daddy collects all amounts due from Customers through its own office staff before installation begins. Subcontractor does not collect, handle, or process any Customer payment, is not an agent of Floor Daddy for any purpose, and will refer every Customer payment question to Floor Daddy. Subcontractor is not responsible for confirming that a Customer has paid before starting work.
7.6 Offsets and backcharges. Floor Daddy may offset against amounts otherwise due only if, within fourteen (14) days of learning of the basis, it issues Subcontractor a written statement setting out in reasonable detail the reason for the offset and its calculated amount, modeled on A.R.S. § 32-1129.02(E). Offsets are limited to documented actual costs reasonably incurred, including materials, labor, and third-party charges, and may not exceed 150% of the disputed amount pending resolution. Floor Daddy will provide supporting documentation on request. Subcontractor may dispute an offset under Section 16.
7.7 Late payment interest. Any amount not paid when due under this Section accrues interest at 1.5% per month until paid. Any amount Subcontractor owes Floor Daddy and does not pay within thirty (30) days after a documented demand accrues interest at the same rate.
7.8 Suspension for non-payment. Consistent with A.R.S. § 32-1129.05(A)(2), nothing in this Agreement limits either Party’s right to suspend performance or terminate for the other Party’s failure to make timely payment. Subcontractor will give Floor Daddy at least seven (7) days’ written notice before suspending or terminating for non-payment.
7.9 Limitations period. Neither Party may bring a claim or action for unpaid work more than two (2) years after the date of the invoice or payment request for that work. Any claim not brought within that period is waived, without regard to any other limitations period set by law. This Section applies equally to both Parties.
8. LIENS, WAIVERS, AND CLAIM RIGHTS
8.1 Statutory waiver exchange. The Parties will exchange lien and claim waivers only on the statutory forms prescribed by A.R.S. § 33-1008. Subcontractor will deliver a conditional waiver and release in exchange for each payment and an unconditional waiver and release upon clearance of that payment. Nothing in this Agreement waives, releases, or impairs any lien or claim right in advance of payment, and any provision that would do so is void under A.R.S. § 33-1008 and has no effect. Forms are attached as Exhibit E.
8.2 Owner-occupied dwellings. Subcontractor acknowledges that A.R.S. § 33-1002 limits lien rights against an owner-occupied dwelling for a party with no direct contractual relationship with the owner-occupant, and that its principal payment security under this Agreement is Section 7 and Arizona’s prompt payment statutes.
8.3 Preliminary notices. Subcontractor may serve a preliminary twenty-day notice under A.R.S. § 33-992.01. Service of a preliminary notice is not a default, is not a claim, and will not be treated as a basis for withholding work or payment.
8.4 Lower-tier claims. If any lien, affidavit of claim, stop payment notice, or lis pendens arising from Subcontractor’s Services or from Subcontractor’s suppliers or lower-tier subcontractors is filed against Floor Daddy, a Customer, or a Project, Subcontractor will, within fifteen (15) days of written demand, cause it to be released of record or bond around it, and will reimburse Floor Daddy’s documented costs and reasonable attorney fees in doing so. This obligation does not apply to a lien or claim filed while a good-faith payment dispute between the Parties is pending, to the extent it relates to the disputed amount.
9. PERMITS
Floor Daddy is responsible for obtaining and paying for all permits and licenses required for the Project, other than Subcontractor’s own contractor’s license, business licenses, registrations, and certifications required under Sections 4 and 12.
10. INSURANCE
10.1 Coverage required. Before accepting any Work Order and continuously through the warranty period in Section 13, Subcontractor will maintain at its own expense:
Coverage
Minimum limit
Commercial General Liability, occurrence form
$1,000,000 per occurrence / $2,000,000 general aggregate / $2,000,000 products-completed operations aggregate
Commercial Automobile Liability, any auto
$1,000,000 combined single limit
Workers’ Compensation
Statutory, with Employer’s Liability of $500,000 each accident, disease each employee, disease policy limit
Tools and equipment
At Subcontractor’s discretion, see Section 11.4
10.2 Workers’ compensation. If Subcontractor is a sole proprietor with no employees and has waived coverage under A.R.S. § 23-961(N), Subcontractor will provide a copy of the waiver in place of a certificate. Subcontractor will notify Floor Daddy in writing within two business days of hiring any employee or engaging any helper, at which point statutory coverage is required before further Services are performed.
10.3 Terms. The CGL policy must: apply separately to Subcontractor’s Services; cover premises-operations, products-completed operations, independent contractors, and contractual liability for the indemnity in Section 11; not exclude the type or volume of the Services or limit the type of structure or number of units; and carry a deductible or self-insured retention of no more than $2,500 unless Floor Daddy agrees otherwise in writing.
10.4 Endorsements. Subcontractor will add Floor Daddy as an additional insured for both ongoing operations and completed operations, on forms at least as broad as CG 20 10 and CG 20 37 or their equivalents, on a primary and non-contributory basis, and will provide a waiver of subrogation in favor of Floor Daddy. Coverage must not be cancelled, non-renewed, or materially reduced without thirty (30) days’ prior written notice to Floor Daddy.
10.5 Statutory limit on additional insured coverage. The Parties acknowledge that under A.R.S. § 32-1159.01(C), an additional insured endorsement furnished in connection with a construction contract involving a Dwelling does not obligate the insurer to indemnify the additional insured for the percentage of fault allocated to that additional insured, although the insurer’s duty to defend under the endorsement is unaffected.
10.6 Certificates. Subcontractor will furnish a certificate of insurance and copies of the required endorsements to its Subcontractor Profile before the first Work Order and at each renewal, and Floor Daddy may suspend Work Orders if any required coverage lapses or expires without replacement on file. Floor Daddy may request declarations pages or certified policy copies. Floor Daddy’s failure to request, obtain, or object to proof of insurance does not waive this Section, and its acceptance of a certificate is not an acceptance of any deficiency.
10.7 Broader coverage. If Subcontractor carries coverage broader or with higher limits than required, this Agreement is deemed to require the broader coverage, including excess and umbrella layers, for claims arising out of the Services.
10.8 Notice of incidents. Subcontractor will notify Floor Daddy and its own insurer in writing immediately of any accident, injury, property damage, or incident related to a Work Order, the Services, or a Project.
11. INDEMNITY
11.1 Scope of indemnity. To the fullest extent permitted by Arizona law, Subcontractor will indemnify and hold harmless Floor Daddy, its members, managers, officers, employees, and agents (each an “Indemnitee”) from and against claims, demands, lawsuits, causes of action, liabilities, damages, losses, and reasonable and necessary attorney fees and costs, on account of bodily injury, personal injury, death, or damage to or loss of tangible property, to the extent caused by: (a) Subcontractor’s breach of this Agreement; (b) the Services performed or materials supplied by Subcontractor or its employees, agents, suppliers, or lower-tier subcontractors; or (c) any negligent or intentional act or omission of Subcontractor or its employees, agents, suppliers, or lower-tier subcontractors.
11.2 Statutory limitation. This Agreement involves a Dwelling. Consistent with A.R.S. § 32-1159.01(A), nothing in this Section requires Subcontractor to insure, indemnify, or hold harmless any Indemnitee against liability for loss or damage resulting from the negligence of that Indemnitee or of the Indemnitee’s other indemnitees, employees, subcontractors, consultants, or agents. Subcontractor’s obligation is limited to its proportionate share of fault.
11.3 Defense. Consistent with A.R.S. § 32-1159.01(D), Subcontractor’s duty to defend is limited to claims arising out of or related to Subcontractor’s own work or operations. Within that limit, the duty to defend is independent of the duty to indemnify and arises upon tender of a claim. Floor Daddy may elect to control its own defense, in which case Subcontractor will reimburse reasonable and necessary defense costs allocable to Subcontractor’s work.
11.4 No bailment. Subcontractor and its personnel are solely responsible for their own tools, materials, and equipment at any Project, and waive any claim against any Indemnitee for loss of or damage to them, except to the extent caused by an Indemnitee’s negligence or intentional act.
11.5 Not limited by workers’ compensation. Subcontractor’s obligations under this Section are not limited by any cap on damages or benefits payable under workers’ compensation, disability, or other employee benefit acts, to the extent permitted by law.
12. SAFETY, HAZARDOUS MATERIALS, AND ENVIRONMENTAL COMPLIANCE
12.1 Safety program. Subcontractor is solely responsible, at its own expense, for the safety of its personnel and for compliance with all occupational health and safety laws, including federal and Arizona OSHA regulations. Subcontractor will furnish and require all necessary personal protective equipment.
12.2 Respirable crystalline silica. Tile demolition, thinset removal, concrete grinding, and similar tasks are covered by 29 CFR 1926.1153. Subcontractor will implement the specified exposure control methods, including integrated water delivery or dust collection, and will maintain a written exposure control plan available on request.
12.3 Suspected asbestos, stop work. Vinyl, VCT, sheet goods, mastic, and adhesives in structures built before approximately 1980 may contain asbestos. Subcontractor will not cut, grind, sand, scrape, or otherwise disturb any material it knows or reasonably suspects contains asbestos. Subcontractor will stop work immediately, secure the area, and notify Floor Daddy. Work resumes only on Floor Daddy’s written direction after testing or abatement. Subcontractor will not perform abatement unless separately licensed and certified to do so.
12.4 Lead-safe work practices. For any Dwelling built before 1978 where the Services disturb painted surfaces, including baseboard removal and demolition, the EPA Lead Renovation, Repair and Painting Rule applies. Subcontractor will either hold current EPA certified renovator firm status and follow lead-safe work practices, or will notify Floor Daddy in writing that it is not certified so the scope can be reassigned. Subcontractor will provide a copy of its certification on request.
12.5 Waste. Subcontractor will dispose of all demolition debris, grout, thinset, adhesive, and other waste lawfully and off site. Subcontractor will not dispose of waste on the Customer’s property or in the Customer’s receptacles, landscaping, or street.
12.6 Site conduct. No person under eighteen (18) years of age may be present at a Project. No alcohol or drugs may be present or used at a Project, and no person may perform Services while impaired. Subcontractor will prohibit the presence of any person not involved in the Services.
13. WARRANTY AND CORRECTIVE SERVICES
13.1 Warranty. Subcontractor warrants to Floor Daddy that all Services will conform to this Agreement and will be free from defects and deficiencies in workmanship. This warranty runs for two (2) years from Completion of the applicable Project, matching the term of the limited warranty Floor Daddy provides to its Customers (the “Customer Warranty”), a copy of which Subcontractor acknowledges receiving. Any longer statutory warranty or period of repose applicable to the Services applies as well.
13.2 Notice and response. Floor Daddy will notify Subcontractor of any warranty claim relating to Subcontractor’s Services. Subcontractor will:
acknowledge the notice within one (1) business day;
contact the Customer and schedule the Corrective Services within three (3) business days; and
complete the Corrective Services within ten (10) business days, or as soon thereafter as Customer access reasonably permits.
Emergency conditions posing a risk of injury or ongoing property damage require same-day response.
13.3 Cost of correction. Subcontractor performs Corrective Services at its own cost, including its labor. Materials previously furnished by Floor Daddy that are needed to correct Subcontractor’s defective work will be furnished by Floor Daddy at Subcontractor’s documented cost.
13.4 Floor Daddy’s cure right. If Subcontractor fails to meet the response times in Section 13.2, Floor Daddy may perform or engage others to perform the Corrective Services. Floor Daddy will invoice Subcontractor for its documented actual costs, supported by invoices and labor records, and may offset those costs under Section 7.6. Floor Daddy will not charge overhead, markup, or profit on Corrective Services performed under this Section. Floor Daddy’s exercise of this right does not waive any other remedy.
13.5 Collateral damage. If Subcontractor’s defective Services damage other work or property, or other work must be removed to correct them, Subcontractor bears the documented cost of correcting, replacing, or repairing that other work or property.
13.6 Obligations after termination. These obligations are supplemented by the Claims and Warranty Agreement. Subcontractor’s warranty and Corrective Services obligations survive termination of this Agreement for the warranty period in Section 13.1 and apply to Projects Subcontractor performed. If Subcontractor is no longer accepting Work Orders, it retains the right and the opportunity to cure its own defects under Section 13.2 before Floor Daddy engages anyone else. If Subcontractor declines or fails to cure, Floor Daddy’s recovery is limited to documented actual cost under Section 13.4. Subcontractor’s aggregate liability for Corrective Services on any single Project is capped at the greater of (a) two times (2x) the Work Order price for that Project, or (b) $2,500. The exclusions from that cap, and the rate at which amounts may be collected, are stated in Sections 4.4, 4.5, 4.7, and 4.9 of the Claims and Warranty Agreement. This cap limits what Floor Daddy may recover from Subcontractor. It does not limit, reduce, or affect any warranty or remedy Floor Daddy owes its Customer.
13.7 Regulatory cooperation. Subcontractor will cooperate in good faith, at no additional charge, with any Arizona Registrar of Contractors complaint under A.R.S. § 32-1155 and any notice-and-repair process under the Purchaser Dwelling Act, A.R.S. § 12-1361 et seq., relating to Services it performed, including site access, documentation, and participation in inspections.
13.8 Attorney fees. In any claim or action arising out of an obligation under this Agreement, the successful or prevailing party is entitled to an award of its reasonable attorney fees and costs. This Section applies equally to both Parties.
14. NON-SOLICITATION AND CUSTOMER RELATIONS
14.1 No diversion. During the term and for [eighteen (18) months] after the last Work Order performed, Subcontractor will not solicit, or perform flooring services for, any Customer whose Project Subcontractor performed or was introduced to through Floor Daddy, for services of the type Floor Daddy provides. Subcontractor will not promote its own services, quote work, or discuss pricing with a Customer, and will refer all such inquiries to Floor Daddy.
14.2 No signage. Subcontractor will not erect signage or otherwise hold itself out at a Project as the contracting party, consistent with Floor Daddy’s status as the licensed contractor of record.
14.3 Remedies. Breach of this Section entitles Floor Daddy to its actual damages, to injunctive relief without the necessity of posting bond, and to its reasonable attorney fees. Floor Daddy may also cease issuing Work Orders. Breach of this Section does not forfeit Subcontractor’s right to payment for Services already properly performed, and does not waive any right of either Party to pursue a claim under Section 16.
15. CONFIDENTIALITY AND DATA
15.1 Subcontractor will keep confidential, and will not use except to perform the Services, Floor Daddy’s pricing schedules, Customer lists and contact information, job costing, margins, business methods, and any other non-public business information. This obligation survives termination for three (3) years, and indefinitely as to Customer personal information.
15.2 Subcontractor will safeguard Customer personal information, will not photograph or publish any Customer’s home other than the close-out photos required by Exhibit A, and will not post Project images identifying a Customer or address without Floor Daddy’s written consent.
15.3 Subcontractor will notify Floor Daddy within twenty-four (24) hours of any loss or unauthorized disclosure of Customer information in its possession.
16. DISPUTE RESOLUTION
16.1 Negotiation. The Parties will first attempt to resolve any dispute by direct negotiation between decision makers within fifteen (15) days of written notice of the dispute.
16.2 Mediation. If negotiation fails, either Party may demand mediation before a mediator experienced in Arizona construction matters. Costs are shared equally. Neither Party must mediate before seeking injunctive or emergency relief.
16.3 Arbitration. Any dispute not resolved by negotiation or mediation will be submitted to binding arbitration under the Federal Arbitration Act, 9 U.S.C. § 1 et seq., before a single arbitrator, applying Arizona law. The arbitration will be conducted in Maricopa County, Arizona, as required by A.R.S. § 32-1129.05(B).
BY SIGNING THIS AGREEMENT, THE PARTIES ARE WAIVING THEIR RIGHT TO FILE A LAWSUIT, TO HAVE A JURY RESOLVE ANY DISPUTE BETWEEN THEM, AND TO APPEAL AN ARBITRATOR’S DECISION TO A COURT OF LAW.
16.4 Small claims carve-out. Either Party may bring a claim within the jurisdictional limit of the Arizona justice courts in that court instead of arbitration, and either Party may seek injunctive relief in a court of competent jurisdiction in Maricopa County.
16.5 Costs. Arbitration filing and arbitrator fees are shared equally, subject to reallocation by the arbitrator. The prevailing party is entitled to reasonable attorney fees under Section 13.8.
16.6 Regulatory rights preserved. Nothing in this Section limits either Party’s right to file or respond to a complaint with the Arizona Registrar of Contractors, the Industrial Commission of Arizona, or any other agency.
17. TERM AND TERMINATION
17.1 Term. This Agreement begins on the Effective Date and continues until terminated under this Section.
17.2 No obligation to offer or accept work. Either Party may decline to offer or accept any future Work Order at any time, for any reason, without notice and without liability. This is not a termination and does not affect accepted Work Orders.
17.3 Removal from an accepted Work Order. Floor Daddy may remove Subcontractor from an accepted Work Order before its expiration only if Subcontractor breaches this Agreement or violates the laws of this state, consistent with A.R.S. § 23-902(D)(4). In that event, Subcontractor is paid a pro rata amount for Services properly performed and materials supplied before removal, subject to offsets properly noticed under Section 7.6.
17.4 Termination of this Agreement. Either Party may terminate this Agreement on seven (7) days’ written notice. Termination does not affect any accepted Work Order then in progress, which remains governed by this Agreement until Completion, unless Subcontractor is removed under Section 17.3.
17.5 Survival. Sections 7, 8, 11, 13, 14, 15, 16, and 18 survive termination.
18. GENERAL
18.1 Notices. Notices must be in writing and are effective when delivered in person, on the third day after mailing by certified mail to the address stated above, or on transmission by email or text message to the contact information stated above with confirmation of receipt. Notices regarding scheduling, Corrective Services, and Work Orders may be given by email or text.
18.2 Assignment. Subcontractor may not assign or transfer its rights or obligations, or the right to payment, without Floor Daddy’s prior written consent, which may be withheld in Floor Daddy’s reasonable discretion. Any attempted assignment without consent is void. Floor Daddy may assign this Agreement in whole or in part. This Agreement binds and benefits the Parties’ permitted successors and assigns.
18.3 Waiver. No waiver is effective unless in a specific, signed writing. No waiver of one breach waives any other breach. Acceptance of payment or performance after a breach is not a waiver, and delay in exercising a right does not waive it.
18.4 Governing law. Arizona law governs, without regard to conflicts principles. Consistent with A.R.S. § 32-1129.05(A)(1), any provision purporting to apply another state’s law or to require proceedings outside Arizona would be void.
18.5 Severability and savings. If any provision is held invalid or unenforceable, it will be modified to the minimum extent necessary to make it enforceable, or if it cannot be, severed, and the rest of this Agreement remains in effect. Any provision that would otherwise be void under A.R.S. § 32-1159.01, § 33-1008, or § 32-1129.05 is deemed reformed to the maximum extent those statutes permit.
18.6 Entire agreement. This Agreement, its Exhibits, and the accompanying documents listed in Section 1.5 are the entire agreement between the Parties regarding the Projects and the Services and supersede all prior agreements, including any prior master agreement, claims agreement, retainer agreement, or contractor agreement between the Parties. In a conflict between this Agreement and a Work Order, invoice, bill of lading, or similar document, this Agreement controls.
18.7 Amendment. This Agreement may be amended only in a writing signed by both Parties.
18.8 Counterparts and electronic signature. This Agreement may be signed in counterparts, including by scanned or electronic signature, each of which is an original and all of which are one instrument.

EXHIBITS. Exhibits A through E (Jobsite, Cleanup and Close-Out Standards; Pricing Schedule; Insurance Requirements; Independent Contractor Agreement under A.R.S. § 23-902(D); and Lien and Claim Waiver Procedure) are incorporated into this Agreement by reference and are provided to Subcontractor together with this Agreement.

This Agreement is executed electronically by the Subcontractor signatory identified below; Floor Daddy’s acceptance is recorded in its contractor management system.$FD01$ where document_type='installer_master';
update public.esign_document_type set consent_text = $FD02$CLAIMS AND WARRANTY AGREEMENT
Floor Daddy, LLC · Arizona ROC License No. 352055
THIS CLAIMS AND WARRANTY AGREEMENT (this “Claims Agreement”) is made as of {{effective_date}}, by and between FLOOR DADDY, LLC, an Arizona limited liability company holding Arizona ROC License No. 352055 (“Floor Daddy”), and {{subcontractor_name}} (“Subcontractor”).
This Claims Agreement supplements Section 13 of the Independent Subcontractor Master Agreement between the Parties (the “Master Agreement”) and uses the definitions given there. If any term of this Claims Agreement conflicts with the Master Agreement, the Master Agreement controls.
1. WHY THIS AGREEMENT EXISTS
1.1 Floor Daddy gives every Customer a written limited warranty on the installed floor. When a Customer reports a problem, Floor Daddy must respond whether or not the installer who performed the work is still taking Work Orders.
1.2 Subcontractor is the party that performed the installation, is licensed to correct it, and is in the best position to make it right. This Claims Agreement sets out who does what when a claim arrives, how responsibility is determined, what it costs, and how long the obligation lasts.
1.3 Subcontractor keeps the first right to fix its own work. Arizona law and Floor Daddy’s own practice favor giving the installing contractor the opportunity to cure. Floor Daddy will not hire another contractor to correct Subcontractor’s work, or charge Subcontractor for doing so, unless Subcontractor has been given notice and a real opportunity to cure under Section 3 and has declined or failed to act.
2. WHAT SUBCONTRACTOR IS RESPONSIBLE FOR
2.1 Covered claims. Subcontractor is responsible, at its own cost, for correcting any defect in a Project it installed that results from:
Defective or non-conforming workmanship by Subcontractor or its personnel;
Failure to follow the manufacturer’s published installation instructions;
Failure to follow the Work Order, applicable building codes, or the workmanship standards published by the Arizona Registrar of Contractors;
Failure to properly prepare, patch, level, or repair a substrate that Subcontractor’s scope required it to prepare;
Damage to the Customer’s home, property, or other finishes caused by Subcontractor or its personnel; or
Failure to identify and report a visible or reasonably discoverable condition before installing over it, as required by Section 5.2 of the Master Agreement.
2.2 Not covered. Subcontractor is not responsible for, and will not be charged for:
Defects in materials furnished by Floor Daddy, including manufacturing defects, dye lot variation, milling defects, and moisture or dimensional problems present on delivery;
Floor Daddy furnishing the wrong product, insufficient quantity, or an inappropriate product for the application;
Conditions Subcontractor reported in writing before installing, where Floor Daddy directed Subcontractor to proceed;
Customer abuse, neglect, improper maintenance, alteration by others, pets, water intrusion, or events outside Subcontractor’s control;
Structural, foundation, slab moisture, or subfloor movement conditions outside Subcontractor’s contracted scope;
Work performed by another contractor, including another installer’s portion of a shared Project; or
Ordinary wear, or normal characteristics of the product disclosed by the manufacturer.
2.3 Multiple installers. If more than one installer worked on a Project, Subcontractor is responsible only for the portion it installed.
2.4 The Final Walkthrough record is the baseline. Every Project closes with a Final Walkthrough conducted by Floor Daddy’s field manager with the Customer, producing dated photographs by room, a punch list showing the disposition of each item, and the Customer’s signed acceptance. Claims are evaluated against that record:
Identified at the Final Walkthrough and cured before acceptance. Closed. No further obligation.
Not present at the Final Walkthrough, appearing later, and workmanship in nature (for example lippage, hollow or loose tile, seam failure, failed transitions, fastener pops, or squeaks). Presumed Subcontractor’s under Section 2.1, subject to Section 2.2.
Not present at the Final Walkthrough, appearing later, and material, environmental, or use-related. Not Subcontractor’s under Section 2.2.
2.5 Effect of acceptance. A condition that was visible at the Final Walkthrough, was not identified, and was accepted by the Customer in writing may not later be charged to Subcontractor as a workmanship defect, unless the condition was concealed at the time or the claim involves a latent defect that would not have been apparent on reasonable inspection.
3. NOTICE, INSPECTION, AND CURE
3.1 Notice. Floor Daddy will notify Subcontractor of a claim by email or text to the contact information in Subcontractor’s Subcontractor Profile, and will include the Project address, the Work Order number, the Customer’s description of the problem, and any photographs Floor Daddy has.
3.2 Response. Subcontractor will:
Acknowledge the notice within one (1) business day;
Contact the Customer and schedule an inspection or the corrective work within three (3) business days; and
Complete the corrective work within ten (10) business days, or as soon thereafter as the Customer’s availability and access reasonably permit.
An emergency posing a risk of injury or continuing property damage requires same-day response.
3.3 Right to inspect before being charged. Subcontractor has the right to inspect the claimed condition before Floor Daddy performs or assigns corrective work. Floor Daddy will not backcharge Subcontractor for corrective work performed by anyone else unless Subcontractor was given that opportunity and either declined it, failed to respond within the times in Section 3.2, or agreed in writing that another party should perform the work.
3.4 Emergency exception. If the condition presents an immediate risk of injury or continuing property damage and Subcontractor cannot respond same-day, Floor Daddy may take immediate action to protect the Customer and the property, and will document the condition with photographs and written notes before and after.
3.5 Confirmation with the field manager. Before charging any claim to Subcontractor, Floor Daddy will compare the claimed condition against the Final Walkthrough record for that Project and confirm the determination with the field manager who conducted that walkthrough. The written determination will state which of the categories in Section 2.4 applies and why.
3.6 Documentation. Every claim charged to Subcontractor must be supported by: written notice under Section 3.1, dated photographs of the condition, a record of Subcontractor’s response or failure to respond, and itemized invoices or labor records supporting the amount charged. Floor Daddy will provide this documentation to Subcontractor on request.
4. COST AND PAYMENT
4.1 Subcontractor’s own labor. Corrective work performed by Subcontractor under Section 3 is performed at Subcontractor’s own cost, including its labor. Subcontractor is not paid separately for correcting its own defective work.
4.2 Materials. Materials previously furnished by Floor Daddy that are needed to correct Subcontractor’s defective work are furnished at Floor Daddy’s documented cost, without markup.
4.3 If Floor Daddy cures. Where Section 3.3 permits, Floor Daddy may perform or assign the corrective work and charge Subcontractor its documented actual cost, consisting of materials at cost, labor at the rate actually paid, and third-party charges actually incurred. Floor Daddy will not add overhead, administrative fees, markup, or profit.
4.4 Cap. Subcontractor’s total liability for corrective work on any single Project is capped at the greater of (a) two times (2x) the total amount Floor Daddy paid or owes Subcontractor for that Project, or (b) $2,500.
4.5 Exclusions from the cap. The cap in Section 4.4 does not apply to:
Third-party claims for bodily injury or damage to property other than Subcontractor’s own work, which are governed by Section 11 of the Master Agreement and are intended to be covered by Subcontractor’s Commercial General Liability policy;
Loss caused by Subcontractor’s gross negligence, willful misconduct, or fraud; or
Loss that would have been covered by insurance Subcontractor was required to maintain under Section 10 of the Master Agreement but failed to keep in force.
4.6 The cap does not affect the Customer. Floor Daddy owes its Customer the full Customer warranty regardless of what it recovers from Subcontractor. Nothing in this Claims Agreement limits, reduces, or conditions any remedy a Customer has against Floor Daddy.
4.7 Collateral damage. If Subcontractor’s defective work damaged other work or property, or other work must be removed to correct it, the documented cost of correcting that other work counts toward the cap in Section 4.4.
4.8 How amounts are collected. Floor Daddy will apply amounts owed under this Claims Agreement in the following order:
First, against the Retention balance held under Section 7.4 of the Master Agreement;
Second, by offset against amounts otherwise payable, following the fourteen-day itemized written statement required by Section 7.6 of the Master Agreement;
Third, by invoice to Subcontractor, payable within thirty (30) days.
4.9 Rate of collection. Floor Daddy will not apply more than twenty-five percent (25%) of any single payment otherwise due Subcontractor toward an outstanding claim balance, so that Subcontractor can continue working while the balance is satisfied. This limit does not apply to the Retention held under Section 7.4 of the Master Agreement, to a final payment after Subcontractor stops accepting Work Orders, or where Subcontractor agrees otherwise in writing.
4.10 Interest. Amounts properly invoiced and unpaid after thirty (30) days accrue interest at 1.5% per month until paid.
4.11 Disputes. Subcontractor may dispute any charge under this Claims Agreement through Section 16 of the Master Agreement. Floor Daddy will not withhold more than 150% of a disputed amount while the dispute is pending. A pending dispute does not relieve Subcontractor of the obligation to respond to a Customer claim under Section 3.
5. DURATION
5.1 Warranty period. Subcontractor’s obligations under this Claims Agreement run for two (2) years from Completion of each Project, matching the term of the limited warranty Floor Daddy provides to its Customers. A copy of the Customer warranty is provided with this Claims Agreement and is available again on request at any time.
5.2 Statutory periods. Where Arizona law imposes a longer statutory warranty or period of repose on the Services, that longer period applies, and this Claims Agreement is expanded but not limited by it.
5.3 Obligations survive the relationship. These obligations continue for the period in Section 5.1 as to Projects Subcontractor performed, whether or not Subcontractor is still accepting Work Orders and whether the relationship ended by termination, non-renewal, or Subcontractor’s own choice. They do not extend to Projects Subcontractor did not perform, and they end when the period in Section 5.1 expires.
5.4 Claims made near the end of the period. A claim is timely if Floor Daddy gives notice under Section 3.1 before the period in Section 5.1 expires, even if the corrective work occurs afterward.
5.5 Time limit on collection. Consistent with Section 7.9 of the Master Agreement, Floor Daddy must bring any claim or action to recover amounts under this Claims Agreement within two (2) years of the date it invoices Subcontractor for them.
6. COOPERATION WITH REGULATORS AND CUSTOMERS
6.1 ROC complaints. If a Customer files a complaint with the Arizona Registrar of Contractors under A.R.S. § 32-1155 relating to a Project Subcontractor installed, Subcontractor will cooperate in good faith and at no additional charge, including providing documentation, site access, and participation in any ROC inspection, and will perform any corrective work directed by agreement or order to the extent it falls within Section 2.1.
6.2 Purchaser Dwelling Actions. If a Customer serves a notice under the Purchaser Dwelling Act, A.R.S. § 12-1361 et seq., Floor Daddy will forward the portion relating to Subcontractor’s work promptly, and Subcontractor will cooperate with the notice-and-repair process, including timely inspection and a written response.
6.3 Customer contact. All communication with a Customer about a claim is limited to scheduling and performing the corrective work. Subcontractor will not discuss fault, pricing, Floor Daddy’s contract with the Customer, or its own services, and will refer those questions to Floor Daddy.
6.4 Records. Each Party will retain Project records, Final Walkthrough records and photographs, and claim documentation for the period in Section 5.1 plus two years. Floor Daddy will make the Final Walkthrough record for a Project available to Subcontractor on request in connection with any claim on that Project.
7. GENERAL
7.1 This Claims Agreement is governed by Arizona law and is subject to the dispute resolution, notice, assignment, waiver, severability, and attorney fee provisions of the Master Agreement.
7.2 This Claims Agreement supersedes any prior claims agreement, warranty agreement, or similar document between the Parties.
7.3 This Claims Agreement may be amended only in a writing signed by both Parties.
7.4 If any provision is held unenforceable, it will be modified to the minimum extent necessary to be enforceable, or severed, and the remainder stays in effect.

This Claims Agreement is executed electronically by the Subcontractor signatory identified below.$FD02$ where document_type='installer_claims';
update public.esign_document_type set consent_text = $FD03$DIRECT DEPOSIT AND ACH PAYMENT AUTHORIZATION
Floor Daddy, LLC · Arizona ROC License No. 352055
Independent Subcontractor Payment Election
Direct deposit is optional. You may choose to be paid by check instead, at any time, by giving Floor Daddy written notice. Choosing direct deposit does not change any payment term of your Independent Subcontractor Master Agreement (the “Master Agreement”), including when payment becomes due.
1. PAYEE INFORMATION
The name below must match the legal name on your Independent Subcontractor Master Agreement, your Form W-9, and your Arizona contractor’s license.
Legal business name: {{subcontractor_name}}
Doing business as, if any: {{dba}}
Contact name: {{contact_name}}
Phone: {{contact_phone}}     Email: {{contact_email}}
2. ACCOUNT INFORMATION
Bank or credit union name: {{bank_name}}
Account type: {{account_type}}
Name on the account: {{account_name}}
Routing number (9 digits): provided by Subcontractor and kept on file
Account number: ending in {{account_last4}} (full number kept on file)
Attach a voided check or a bank-issued account verification letter. Deposit slips are not accepted.
3. AUTHORIZATION
By signing below, Subcontractor authorizes Floor Daddy, LLC to initiate credit entries to the account identified above for amounts payable under the Master Agreement, and authorizes the financial institution named above to accept those entries.
3.1 Prenote. Floor Daddy may send a zero-dollar verification entry before the first deposit. The first one or two payments may be issued by check while account details are verified.
3.2 Delays and fees. Floor Daddy is not responsible for delays caused by the receiving institution’s funding timelines, nor for any fee the receiving institution charges Subcontractor. Payment is considered made when Floor Daddy initiates the transfer.
3.3 Correction of a demonstrated overpayment. Subcontractor authorizes Floor Daddy to initiate a debit entry to the account above solely to correct a demonstrated erroneous overpayment, subject to all of the following:
The debit is limited to the amount of the overpayment;
Floor Daddy provides written notice with supporting detail at least five (5) business days before initiating the debit; and
This authorization does not extend to backcharges, corrective work costs, warranty claims, retention, or any disputed amount. Those are handled only under Section 7.6 of the Master Agreement and the Claims and Warranty Agreement, and may never be collected by debiting this account.
3.4 Changes and cancellation. This authorization stays in effect until Subcontractor changes or cancels it in writing. A change or cancellation takes effect on the first payment cycle beginning at least three (3) business days after Floor Daddy receives the notice. Subcontractor will notify Floor Daddy immediately if the account is closed or the account details change.
3.5 Authority and accuracy. Subcontractor certifies that it is authorized to direct deposits to and, to the limited extent stated in Section 3.3, debits from the account above, and that the information provided is accurate.
3.6 Compliance. Entries are subject to the NACHA Operating Rules and applicable law. Subcontractor may dispute an unauthorized entry with its financial institution and retains all rights under those rules.

By signing electronically below, Subcontractor certifies the payee and account information above is accurate and authorizes the direct deposit terms in this authorization.$FD03$ where document_type='installer_ach';
