-- Same fix as 0141, on the two tables the Communication Hub actually reads.
--
-- 0141 stopped ghl_message and ghl_conversation re-checking permissions per row,
-- and the Hub's query went from timing out to 13.1 seconds. Still unusable, and
-- the plan said exactly where the time went:
--
--     Seq Scan on lead             Filter: can_view('leads')          11,767 ms
--     Index Scan on communication  ... can_view('communication')       1,126 ms
--
-- Eleven seconds to authorise 17,459 lead rows one at a time, for a question
-- whose answer does not vary by row: either this user may see leads or they may
-- not.
--
-- Wrapping the call in a scalar subquery makes that explicit to the planner.
-- `(select can_view('leads'))` references no column, so it becomes an InitPlan
-- evaluated once per query. The authorisation is identical -- same function,
-- same argument, same answer -- it is only asked once instead of 17,459 times.
--
-- Measured end to end on the Hub's actual query, as a signed-in user:
--
--     before 0141      timed out, screen empty
--     after  0141      13,112 ms
--     after  0142         328 ms
--
-- The predicates below are otherwise reproduced EXACTLY as they were, including
-- communication's `deleted_at IS NULL` and its is_org_admin() escape hatch.
-- These are security policies: the change must be provably just the wrapping,
-- because anything else silently widens or narrows who can read customer
-- messages.
--
-- THIS IS NOT ISOLATED, and the rest is deliberately left alone. 89 policies
-- across 82 tables share the shape, generated by 0002's loop -- harmless while a
-- table is small, a timeout once it is not. `lead` and `communication` are fixed
-- here because they were the ones breaking a live screen. Rewriting 87 more
-- security policies is not something to do in the same breath as an outage fix;
-- it wants its own change, with each predicate verified before and after.
drop policy if exists mod_select on public.lead;
create policy mod_select on public.lead
  for select to authenticated
  using ((select public.can_view('leads')));

drop policy if exists mod_select on public.communication;
create policy mod_select on public.communication
  for select to authenticated
  using (
    ((deleted_at is null) and (select public.can_view('communication')))
    or (select public.is_org_admin())
  );
